<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RequestLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestLogRepository extends EntityRepository
{
    /**
     * @param \DateTime $from
     * @param \DateTime $to
     * @return int
     * @throws \Doctrine\ORM\Query\QueryException
     */
    public function countRequests(\DateTime $from, \DateTime $to): int
    {
        return (int)$this->createQueryBuilder('r')
            ->select('count(r.id)')
            ->where('r.createdAt > :from')
            ->andWhere('r.createdAt < :to')
            ->setParameter('from', $from->format('Y-m-d H:i:s'))
            ->setParameter('to', $to->format('Y-m-d H:i:s'))
            ->getQuery()
            ->getSingleScalarResult();
    }
}
